---
# Chart Releaser config
# See: https://github.com/helm/chart-releaser

sign: false
skip-existing: false
make-release-latest: true
packages-with-index: true
release-name-template: "{{ .Name }}-{{ .Version }}"
index-path: index.yaml
pages-index-path: index.yaml
owner: raulstechtips
repo: infisical-standalone-db-secure-wrapper
