---
# Chart Releaser config
# See: https://github.com/helm/chart-releaser

sign: false
skip-existing: true
make-release-latest: true
packages-with-index: true
release-name-template: "{{ .Name }}-{{ .Version }}"
index-path: index.yaml
