---
name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚠️ Security'
    labels:
      - 'security'
  - title: '🔄 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
autolabeler:
  - label: 'breaking'
    title:
      - '/breaking/i'
    body:
      - '/breaking change/i'
  - label: 'feature'
    title:
      - '/feat/i'
      - '/feature/i'
  - label: 'fix'
    title:
      - '/fix/i'
      - '/hotfix/i'
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'docs'
    title:
      - '/docs/i'
      - '/documentation/i'
  - label: 'security'
    title:
      - '/security/i'
  - label: 'deps'
    title:
      - '/deps/i'
      - '/dependencies/i'
exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'wontfix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'docs'
      - 'documentation'
      - 'dependencies'
      - 'deps'
  default: patch
sort-by: 'merged_at'
sort-direction: 'ascending'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Contributors

  $CONTRIBUTORS
