---
name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Helm dependency update
        run: helm dependency update .

      - name: YAML Lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: config.yamllint.yaml
          yamllint_strict: false
          yamllint_comment: true

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint Helm chart
        run: ct lint --config .github/ct.yaml

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Helm dependency update
        run: helm dependency update .

      - name: Install Helm unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run Deployment Patch Tests
        run: helm unittest --color -f tests/unit/deployment-patch_test.yaml .

      - name: Run Migration Job Patch Tests
        run: helm unittest --color -f tests/unit/migration-job-patch_test.yaml .

  security-scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Helm dependency update
        run: helm dependency update .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
